#[mysql]
#host = '217.21.90.185'
#port = '3306'
#database = 'u161125988_etd_streamlit'
#user = 'u161125988_ps_23'
#password = 'Exdiibt3Python'
#
#
#[snowflake]
#user = "MSH23"
#password = "Exdiibt3Python"
#account = "ZP47216"
#warehouse = "COMPUTE_WH"
#database = "ETD"
#schema = "PUBLIC"
#
#
##supabase_url = "https://vafkqsipcovbwhbeatcn.supabase.co"
##supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZmtxc2lwY292YndoYmVhdGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzc4NTI4NTQsImV4cCI6MTk5MzQyODg1NH0.f8r1bI8tGr7s_dVFktuRw1zaZ4v3VwzDi5e4ELRNZiI"
#
[postgres]
host = "db.vafkqsipcovbwhbeatcn.supabase.co"
port = '5432'
dbname = "postgres"
user = "postgres"
password = "Exdiibt3Python"
#
#supabase_url = "https://vafkqsipcovbwhbeatcn.supabase.co"
#supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZmtxc2lwY292YndoYmVhdGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE2Nzc4NTI4NTQsImV4cCI6MTk5MzQyODg1NH0.f8r1bI8tGr7s_dVFktuRw1zaZ4v3VwzDi5e4ELRNZiI"